### ISSUE TITLE
Only black images are produced with --skip parameter, without --skip I always get NSFW block

### ISSUE THREAD

**Issue by cl1nk2** [fboulnois/stable-diffusion-docker#80] opened 2023-04-24 13:06 UTC
GPU is a 1660, I checked and drivers are all up to date, torch seems to recognize GPU correctly. I'm running Windows 11, Docker runs under WSL2.

I tried with different parameters, tried onxx, doesn't work any of them (with onxx it doesn't start the iteration process, just ends and gives black image).

Here is what I get in terminal:
```
./build.sh run --height 256 --width 256 --attention-slicing --xformers-memory-efficient-attention --half --skip "abstract art"
load pipeline start: 2023-04-24T13:04:55.748155
vae/diffusion_pytorch_model.safetensors not found
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
loaded models after: 2023-04-24T13:05:12.496854
100%|██████████| 50/50 [00:36<00:00,  1.38it/s]
/usr/local/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py:1363: RuntimeWarning: invalid value encountered in cast
  images = (images * 255).round().astype("uint8")
completed pipeline: 2023-04-24T13:05:52.171115
```

Thank you very much in advance!

**Comment by fboulnois** [comment] 2023-04-25 00:17
I am able to reproduce this issue, but unfortunately I don't have a solution. This problem seems to be related to https://github.com/huggingface/diffusers/issues/2107 . Recent updates to the underlying library (and to the safety checker?) make generating images smaller than 512x512 much more unstable.

**Comment by fboulnois** [comment] 2023-05-27 15:55
Closing since this is out of my control.

**Closed as not planned by fboulnois** 2023-05-27 15:55 UTC
